version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - Attributify
  - cientos
  - Deditor
  - duckdb
  - etcdctl
  - healthcheck
  - huggingface
  - iconify
  - initdb
  - isready
  - kebabcase
  - martinbeentjes
  - matchall
  - milvus
  - minioadmin
  - Moeru
  - mysqladmin
  - nolyfill
  - ofetch
  - oklch
  - PCA
  - pglite
  - pgvecto
  - pgvector
  - pinia
  - reka
  - shadcn
  - Splitpanes
  - sslmode
  - Supabase
  - tanstack
  - taze
  - tensorchord
  - tresjs
  - tsdown
  - TSNE
  - UMAP
  - unocss
  - unplugin
  - vueuse
  - xsai
ignoreWords: []
import: []
