version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - amhandler
  - amname
  - amtype
  - Attributify
  - cientos
  - Deditor
  - duckdb
  - etcdctl
  - guiiai
  - healthcheck
  - huggingface
  - iconify
  - indcheckxmin
  - indclass
  - indcollation
  - indexdef
  - indexprs
  - indexrelid
  - indimmediate
  - indisclustered
  - indisexclusion
  - indislive
  - indisprimary
  - indisready
  - indisreplident
  - indisunique
  - indisvalid
  - indkey
  - indnatts
  - indnkeyatts
  - indnullsnotdistinct
  - indoption
  - indpred
  - indrelid
  - initdb
  - isready
  - kebabcase
  - Logg
  - martinbeentjes
  - matchall
  - milvus
  - minioadmin
  - Moeru
  - mysqladmin
  - nolyfill
  - nspacl
  - nspname
  - nspowner
  - ofetch
  - oid
  - oklch
  - PCA
  - pglite
  - pgvecto
  - pgvector
  - pinia
  - regclass
  - regnamespace
  - reka
  - relacl
  - relallvisible
  - relam
  - relchecks
  - relfilenode
  - relforcerowsecurity
  - relfrozenxid
  - relhasindex
  - relhasrules
  - relhassubclass
  - relhastriggers
  - relispartition
  - relispopulated
  - relisshared
  - relkind
  - relminmxid
  - relname
  - relnamespace
  - relnatts
  - reloftype
  - reloptions
  - relowner
  - relpages
  - relpartbound
  - relpersistence
  - relreplident
  - relrewrite
  - relrowsecurity
  - reltablespace
  - reltoastrelid
  - reltuples
  - reltype
  - shadcn
  - Splitpanes
  - sslmode
  - Supabase
  - tanstack
  - taze
  - tensorchord
  - tresjs
  - tsdown
  - TSNE
  - UMAP
  - unocss
  - unplugin
  - vueuse
  - xsai
ignoreWords: []
import: []
