name: Release App

permissions:
  contents: write

on:
  release:
    types:
      - prereleased

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: macos-13
            artifact: darwin-x64
            ext: dmg
          - os: macos-latest
            artifact: darwin-arm64
            ext: dmg
          - os: ubuntu-latest
            artifact: linux-x64
            ext: AppImage
          # - os: ubuntu-24.04-arm
          #   artifact: linux-arm64
          #   ext: AppImage
          - os: windows-latest
            artifact: windows-x64-setup
            ext: exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: |
          pnpm run build:packages
          pnpm run build:electron

      - id: version
        run: |
          echo VERSION=$(pnpm exec tsx scripts/get-package-json-version.ts) >> $GITHUB_ENV

      - name: Upload To GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Deditor-v${{ steps.version.outputs.VERSION }}-${{ matrix.artifact }}.${{ matrix.ext }}
          generate_release_notes: true
